version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: hydora:latest
    volumes:
      - type: bind
        source: ../src/010_simple_cli_app
        target: /workdir
    working_dir: /workdir
    command: python my_app.py db.driver=mysql db.user=omry db.pass=secret
