version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: hydora:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
    working_dir: /workdir
    command: python my_app.py db=postgresql db.timeout=20
